"""add logo url in job_boards

Revision ID: 153d5eb2350e
Revises: e3d524a44d96
Create Date: 2025-11-24 16:11:52.583191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153d5eb2350e'
down_revision: Union[str, Sequence[str], None] = 'e3d524a44d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_boards', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_boards', 'logo_url')
    # ### end Alembic commands ###
